### ISSUE TITLE
Object(...) is not a function at n.initEventStream

### ISSUE THREAD

**Issue by ankitsanghvi2** [gmerabishvili/angular-ng-autocomplete#102]
Hello, All
When i am configuring this its throwing error at below piece of code, it seems fromEvent is undefined each time. and its throwing this type of error on page load only, so my target is to call custom service on change event. I am not able to continue. Could anyone suggest if i am missing anything.

`this.inputKeyUp$ = Object(fs.fromEvent)(this.searchInput.nativeElement, "keyup").pipe(Object(sl.a)(function(n) {
                    return n
                }));`

is it related to any node package version?

**Comment by gmerabishvili** [comment]
@ankitsanghvi2 Hello, please refer to example here: https://stackblitz.com/edit/angular-ng-autocomplete
There shouldn't be any issue regarding node package version.

**Comment by Christian-RM** [comment]
Hello, I have the same issue on the init of the component that has the <ng-autocomplete> component, I get this error 

ERROR TypeError: Object(...) is not a function
    at AutocompleteComponent.initEventStream (angular-ng-autocomplete.js:674)
    at AutocompleteComponent.ngOnInit (angular-ng-autocomplete.js:216)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at prodCheckAndUpdateNode (core.js:14602)
    at Object.eval [as updateDirectives] (InputTypeAheadComponent.ngfactory.js:100)
    at Object.updateDirectives (core.js:14324)
    at checkAndUpdateView (core.js:13844)
    at callViewAction (core.js:14195)
defaultErrorLogger @ core.js:1449
ErrorHandler.handleError @ core.js:1510
eval @ core.js:5925
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4708
ApplicationRef.tick @ core.js:5925
eval @ core.js:5751
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4760
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4577
next @ core.js:5751
schedulerFn @ core.js:4342
SafeSubscriber.__tryOrUnsub @ Subscriber.js:243
SafeSubscriber.next @ Subscriber.js:190
Subscriber._next @ Subscriber.js:131
Subscriber.next @ Subscriber.js:95
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4322
checkStable @ core.js:4725
onLeave @ core.js:4804
onInvokeTask @ core.js:4754
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566


![image](https://user-images.githubusercontent.com/49409190/92671026-819faa00-f2d2-11ea-842c-c01c2b606d58.png)

And after that I can't use the (inputChanged) function, it never fires, but that is the only one because the (inputFocused) and (selected) do work
