### ISSUE TITLE
Questionable copyright ethics

### ISSUE THREAD

**Issue by cxspxr** [gmerabishvili/angular-ng-autocomplete#134]
It's generally not ok if there is a contribution made to an open-source project, and the author of the project closes a PR and re-commits the code that has been contributed by others as his own.

I am talking about #105 #90 #89 #73 #64 #54 #48 #39 #132 and others.
~~Generally, the contribution that has been made by someone is authored by that person. It's called copyright violation if you take the others' code and author it as your own, if I'm not mistaken.~~ Okay, ***maybe*** it's not a violation of MIT, but chances are it is. Yet it is still questionable ethics.

Otherwise it's good to create `CONTRIBUTING.md` and state there that all the contributions will be ~~re-authored~~ stolen. To make it clear for future contributors.

I won't do anything with that, it just looks bad and it's worth to re-think in future to improve it at the early stage while it doesn't really affect the reputation yet.

Worth reading a story around @kataras and https://github.com/kataras/iris in spare time:
https://www.reddit.com/r/golang/comments/b481q7/a_warning_about_githubcomkatarasiris/

**Comment by gmerabishvili** [comment]
@cxspxr Hey, I never thought that it would cause any controversy, because in most cases I always had to test those PRs on my machine and later whenever I had time I was pushing those changes all together. Also, I must say that  there have never been  any big feature from any PR, but some small fixes only and in some  cases I had to change something or completely ignore the PR, because it was breaking other stuff.  In your case I had to change the name of the property to 'customFilter' and that's why I closed it and didn't merge right away. I didn't know if it mattered for you anyway : ) But no problem, I can merge it now and I'll  rename that property  later. Thank you.

**Comment by cxspxr** [comment]
No, as I stated before, it's not that I want you to do some extra work, it's the point for you to think about. 
Because there are/were a lot of situations in which reputation of authors has become questionable after similar cases. Just be aware and consider it for further contributions.

**Comment by cxspxr** [comment]
Just take it in account in future

**Comment by gmerabishvili** [comment]
@cxspxr  Yes, maybe, I was never overwhelmed by many big PRs : ) , but anyway that's nice point.  Thank you for your contribution (Y)
