### ISSUE TITLE
Performance issues on big option counts

### ISSUE THREAD

**Issue by LukeSamkharadze** [gmerabishvili/angular-ng-autocomplete#154]
[Stackblitz Example](https://stackblitz.com/edit/angular-ng-autocomplete-with-forms-jsrh9d?file=src/app/app.component.html)

I think using **Virtual scroll** from `cdkScrollable` would solve this problem. **Virtual scroll** enables us to render options that are visible

**Comment by gmerabishvili** [comment]
@LukeSamkharadze  Check the docs. There's infinite scroll option there already: `(scrolledToEnd) - Event is emitted when scrolled to the end of items. Can be used for loading more items in chunks.` Beside that, I don't want to have any other dependencies for this library, that's why I didn't use any, including CDK.

**Comment by LukeSamkharadze** [comment]
Then you also have to unload chunks, how would you do that? It gets pretty complex

Also just using `scrolledToEnd` would give false impressions on how many options you have, you scroll to the end, then few new options appear... scroll... appear.... and so on.

Workaround is possible, but its much simpler to use `cdk`

**Comment by gmerabishvili** [comment]
@LukeSamkharadze  Yes, as I guess you're talking about **virtual scrolling**, but at this moment ng-autocomplete supports **infinite scroll** only. They are two different strategies for scrolling behaviour. Maybe I'll implement CDK style virtual scroll sometime in the future, but for now I'll keep the library without any dependency  : )
